services:
  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-server
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/final_capstone
      SPRING_DATASOURCE_USERNAME: final_capstone_appuser
      SPRING_DATASOURCE_PASSWORD: finalcapstone
    ports:
      - "9000:9000"
